In [1]:
import torch
import numpy as np
torch.__version__

'1.5.1'

In [4]:
x = torch.rand(2, 3)
x

tensor([[0.1699, 0.2649, 0.1284],
        [0.5649, 0.3288, 0.3442]])

In [5]:
x.shape

torch.Size([2, 3])

In [6]:
x.size

<function Tensor.size>

In [7]:
x.size()

torch.Size([2, 3])

In [8]:
y = torch.rand(2, 3, 4, 5)

In [9]:
y

tensor([[[[0.0679, 0.0181, 0.8771, 0.4981, 0.9268],
          [0.2888, 0.9798, 0.4050, 0.9295, 0.4226],
          [0.0303, 0.1286, 0.6003, 0.1653, 0.6864],
          [0.6388, 0.5294, 0.4820, 0.2435, 0.2200]],

         [[0.9689, 0.9336, 0.8257, 0.6612, 0.0437],
          [0.1551, 0.6110, 0.1406, 0.6514, 0.1097],
          [0.0744, 0.0475, 0.1189, 0.4488, 0.4939],
          [0.2437, 0.9962, 0.5436, 0.4817, 0.2064]],

         [[0.8793, 0.6674, 0.3665, 0.6914, 0.0446],
          [0.3989, 0.5340, 0.6743, 0.2234, 0.8359],
          [0.1446, 0.9272, 0.9059, 0.7548, 0.7218],
          [0.8857, 0.8042, 0.3978, 0.0092, 0.4544]]],


        [[[0.3641, 0.0899, 0.9844, 0.8684, 0.9409],
          [0.0488, 0.0362, 0.3301, 0.7939, 0.9722],
          [0.5820, 0.3028, 0.4391, 0.0313, 0.8171],
          [0.3800, 0.7098, 0.3864, 0.3520, 0.5169]],

         [[0.6931, 0.7973, 0.3918, 0.7416, 0.3316],
          [0.3050, 0.0809, 0.8488, 0.9980, 0.0988],
          [0.8081, 0.8826, 0.3211, 0.1845, 0.2524],
  

In [10]:
scalar = torch.tensor(3.1433223)
print(scalar)
scalar.size()

tensor(3.1433)


torch.Size([])

In [11]:
scalar.item()

3.143322229385376

In [14]:
from torch import tensor

In [18]:
tensor = torch.tensor([3.1433223])

In [19]:
long = tensor.long()
long

tensor([3])

In [20]:
half=tensor.half()
half

tensor([3.1426], dtype=torch.float16)

In [21]:
int_t=tensor.int()
int_t

tensor([3], dtype=torch.int32)

In [22]:
a = torch.randn((3, 2))
numpy_a = a.numpy()
print(numpy_a)

[[ 0.39766577 -0.22742875]
 [ 0.32777357  0.05551188]
 [-0.5097731   0.03565705]]


In [23]:
torch_a = torch.from_numpy(numpy_a)
torch_a

tensor([[ 0.3977, -0.2274],
        [ 0.3278,  0.0555],
        [-0.5098,  0.0357]])

In [24]:
cpu_a = torch.rand(4, 3)
cpu_a.type()

'torch.FloatTensor'

In [25]:
gpu_a = cpu_a.cuda()
gpu_a.type()

AssertionError: Torch not compiled with CUDA enabled

In [26]:
rnd = torch.rand(5, 3)

In [27]:
rnd

tensor([[0.4910, 0.8346, 0.8295],
        [0.6978, 0.7755, 0.6342],
        [0.3785, 0.1714, 0.8530],
        [0.9050, 0.6823, 0.4752],
        [0.9776, 0.1181, 0.3961]])

In [28]:
one = torch.ones(2, 2)
one

tensor([[1., 1.],
        [1., 1.]])

In [29]:
zero = torch.zeros(2, 2)

In [30]:
zero

tensor([[0., 0.],
        [0., 0.]])

In [31]:
eye = torch.eye(2, 2)
eye

tensor([[1., 0.],
        [0., 1.]])

In [32]:
x = torch.randn(3, 3)
x

tensor([[ 1.1833,  0.0323, -0.1669],
        [-0.1070, -0.7208,  1.1240],
        [ 0.9293, -0.8853,  0.6449]])

In [33]:
max_value, max_idx = torch.max(x, dim = 1)

In [34]:
max_value, max_idx

(tensor([1.1833, 1.1240, 0.9293]), tensor([0, 2, 0]))

In [35]:
sum_x = torch.sum(x, dim=1)

In [36]:
sum_x

tensor([1.0487, 0.2962, 0.6889])

In [37]:
y = torch.randn(3, 3)
z = x + y
z

tensor([[ 2.0159, -0.6189,  0.8667],
        [ 0.1668, -1.7483, -0.3116],
        [ 0.4525, -0.4213,  2.6421]])

In [38]:
x.add_(y)

tensor([[ 2.0159, -0.6189,  0.8667],
        [ 0.1668, -1.7483, -0.3116],
        [ 0.4525, -0.4213,  2.6421]])