In [1]:
import torch
torch.__version__

'1.5.1'

In [10]:
x = torch.rand(5, 5, requires_grad = True)
x

tensor([[0.0077, 0.7999, 0.7600, 0.1780, 0.3539],
        [0.0755, 0.0871, 0.5288, 0.5404, 0.8689],
        [0.3211, 0.9853, 0.5106, 0.8021, 0.6981],
        [0.4541, 0.9623, 0.0407, 0.7970, 0.5576],
        [0.8727, 0.6407, 0.2285, 0.9937, 0.7050]], requires_grad=True)

In [11]:
y = torch.rand(5, 5, requires_grad = True)
y

tensor([[0.4317, 0.8750, 0.4761, 0.8769, 0.3491],
        [0.8276, 0.9852, 0.0237, 0.1278, 0.6382],
        [0.5970, 0.8898, 0.3756, 0.8500, 0.2060],
        [0.9121, 0.4841, 0.6779, 0.5067, 0.3290],
        [0.0675, 0.1148, 0.6396, 0.1419, 0.0035]], requires_grad=True)

In [13]:
z = torch.sum(x+y)
z

tensor(26.1766, grad_fn=<SumBackward0>)

In [16]:
z.backward()
print(x.grad)
print(y.grad)

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])


In [17]:
x = torch.rand(5, 5, requires_grad = True)
y = torch.rand(5, 5, requires_grad = True)
z = x ** 2 + y ** 3
z

tensor([[0.1954, 0.3301, 0.2370, 0.7551, 0.9938],
        [0.0911, 0.7931, 0.0949, 0.1876, 0.9396],
        [0.9772, 0.9469, 0.5287, 0.3106, 0.4198],
        [0.0187, 0.3225, 0.3821, 0.6035, 1.2916],
        [0.8752, 0.3719, 0.5936, 1.2775, 0.9913]], grad_fn=<AddBackward0>)

In [19]:
z.backward(torch.ones_like(x))
print(x.grad)

tensor([[0.8830, 0.4567, 0.6886, 0.5426, 1.9938],
        [0.5190, 1.6793, 0.6144, 0.8663, 1.9328],
        [0.5650, 1.9440, 1.4542, 0.2753, 1.1985],
        [0.1657, 1.1126, 1.1032, 1.3203, 1.9596],
        [1.8024, 0.3664, 1.4866, 1.8304, 1.9771]])


In [20]:
dir(z)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmul__',
 '__rpow__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__

In [21]:
print(x.is_leaf)
print(z.is_leaf)

True
False


In [22]:
z.grad_fn

In [23]:
dir(z.grad_fn)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_register_hook_dict',
 'metadata',
 'name',
 'next_functions',
 'register_hook',
 'requires_grad']

In [24]:
z.grad_fn.next_functions

((<PowBackward0 at 0x7fc5f7623f98>, 0), (<PowBackward0 at 0x7fc5f7ddb208>, 0))

In [25]:
xg = z.grad_fn.next_functions[0][0]
xg

In [26]:
dir(xg)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_register_hook_dict',
 'metadata',
 'name',
 'next_functions',
 'register_hook',
 'requires_grad']

In [27]:
x_leaf = xg.next_functions[0][0]
type(x_leaf)

AccumulateGrad

In [28]:
x_leaf.variable

tensor([[0.4415, 0.2284, 0.3443, 0.2713, 0.9969],
        [0.2595, 0.8397, 0.3072, 0.4332, 0.9664],
        [0.2825, 0.9720, 0.7271, 0.1376, 0.5993],
        [0.0829, 0.5563, 0.5516, 0.6601, 0.9798],
        [0.9012, 0.1832, 0.7433, 0.9152, 0.9885]], requires_grad=True)

In [29]:
x

tensor([[0.4415, 0.2284, 0.3443, 0.2713, 0.9969],
        [0.2595, 0.8397, 0.3072, 0.4332, 0.9664],
        [0.2825, 0.9720, 0.7271, 0.1376, 0.5993],
        [0.0829, 0.5563, 0.5516, 0.6601, 0.9798],
        [0.9012, 0.1832, 0.7433, 0.9152, 0.9885]], requires_grad=True)

In [31]:
id(x_leaf.variable)

140488224616168

In [32]:
id(x)

140488224616168

In [33]:
assert(id(x_leaf.variable) == id(x))

In [34]:
from torch.autograd.function import Function

In [35]:
class Mulconstant(Function):
    @staticmethod
    def forward(ctx, tensor, constant):
        ctx.constant = constant
        return tensor * constant
    
    @staticmethod
    def backward(ctx, grad_output):
        return grad_output, None

In [37]:
a = torch.rand(3, 3, requires_grad = True)
b = Mulconstant.apply(a, 5)
print(a)
print(b)

tensor([[0.9809, 0.7438, 0.1344],
        [0.3736, 0.3009, 0.4896],
        [0.0232, 0.5478, 0.0374]], requires_grad=True)
tensor([[4.9047, 3.7188, 0.6719],
        [1.8681, 1.5044, 2.4478],
        [0.1159, 2.7388, 0.1868]], grad_fn=<MulconstantBackward>)


In [38]:
b.backward(torch.ones_like(a))

In [39]:
a.grad

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])